openapi: "3.0.0"
info:
  title: "FTGO Phase 2 Livecode 2 API Contract"
  description: "Pastikan semua endpoint pada livecode mengikuti ketentuan yang tercantum pada dokumen ini. Tanyakan pada instruktur/tim akademik yang bertugas jika ada hal yang perlu diklarifikasi dan ditanyakan. Kesalahan pemahaman requirement bisa mengakibatkan pengurangan nilai livecode"
  version: "1.0"
  contact:
    name: "FTGO Academic Team"
servers:
  - url: "http://localhost:8080"
    description: "development/livecode"

paths:
  '/users/register':
    post:
      tags:
        - user
      summary: "register user baru"
      description: "register user baru ke dalam aplikasi"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registerUser"
      responses:
        201:
          description: "response berhasil registrasi user baru"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "success register"
                  user:
                    $ref: "#/components/schemas/user"
        400:
          $ref: "#/components/responses/badRequest"
        500:
          $ref: "#/components/responses/internalServerError"
  '/users/login':
    post:
      tags:
        - user
      summary: "login user yang sudah terdaftar"
      description: "login user yang sebelumnya sudah berhasil melakukan registrasi, akan membalikan data akses token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginUser"
      responses:
        200:
          description: "response berhasil login"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/loginSuccess"
        400:
          $ref: "#/components/responses/badRequest"
        401:
          $ref: "#/components/responses/loginFailedInvalidCred"
        500:
          $ref: "#/components/responses/internalServerError"    

  '/articles':
    post:
      tags:
        - article
      summary: "membuat data article"
      description: "membuat data appointment baru berdasarkan barber dan waktu appointment"

      parameters:
        - $ref: "#/components/parameters/authorization"
      security:
        - ApiKeyAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postArticle"
      responses:
        200:
          description: "response berhasil membuat article"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    example: "success create article"
                  article:
                    $ref: "#/components/schemas/article"
              
        400:
          $ref: "#/components/responses/badRequest"
        401:
          $ref: "#/components/responses/unauthorized"
        500:
          $ref: "#/components/responses/internalServerError"
    get:
      tags:
        - article
      summary: "menamilkan data articles"
      description: "menampilkan seluruh data article"

      parameters:
        - $ref: "#/components/parameters/authorization"
      security:
        - ApiKeyAuth: []

      responses:
        200:
          description: "repsonse berhasil"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/article"
        401:
          $ref: "#/components/responses/unauthorized"
        500:
          $ref: "#/components/responses/internalServerError"
  '/articles/:id':
    delete:
      tags:
        - article
      summary: "menghapus data article berdasarkan ID"
      description: "menghapus data article berdasarkan ID"

      parameters:
        - $ref: "#/components/parameters/authorization"
        - $ref: "#/components/parameters/articleId"
      security:
        - ApiKeyAuth: []

      responses:
        200:
          description: "repsonse berhasil"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    default: "success delete article with id [ID]"
        401:
          $ref: "#/components/responses/unauthorized"
        403:
          $ref: "#/components/responses/forbidden"
        404:
          $ref: "#/components/responses/notFound"
        500:
          $ref: "#/components/responses/internalServerError"
  
  '/likes':
    post:
      tags:
        - article
      summary: "membuat data likes"
      description: "membuat data likes baru untuk sebuah article"

      parameters:
        - $ref: "#/components/parameters/authorization"
      security:
        - ApiKeyAuth: []
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/postLikes"
      responses:
        200:
          description: "repsonse berhasil"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    default: "success add likes to article with id [ID]"
        400:
          $ref: "#/components/responses/badRequest"
        401:
          $ref: "#/components/responses/unauthorized"
        404:
          $ref: "#/components/responses/notFound"
        500:
          $ref: "#/components/responses/internalServerError"
  '/likes/:id':
    delete:
      tags:
        - article
      summary: "menghapus data likes"
      description: "menghapus data likes untuk sebuah article berdasarkan article_id"

      parameters:
        - $ref: "#/components/parameters/authorization"
        - $ref: "#/components/parameters/articleId"
      security:
        - ApiKeyAuth: []
      responses:
        200:
          description: "repsonse berhasil"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                    default: "success remove likes from article with id [ID]"
        401:
          $ref: "#/components/responses/unauthorized"
        403:
          $ref: "#/components/responses/forbidden"
        404:
          $ref: "#/components/responses/notFound"
        500:
          $ref: "#/components/responses/internalServerError"

components:
  parameters:
    authorization:
      name: Authorization
      description: "authorization key yang didapatkan ketika berhasil login"
      in: header
      schema:
        type: "string"
    articleId:
      name: "id"
      in: "path"
      description: "parameter id akan yang akan digunakan untuk keperluan action pada endpoint"
      required: true
      schema:
        type: "number"
  schemas:
    registerUser:
      type: "object"
      properties:
        full_name:
          type: "string"
          default: "example full name"
        username:
          type: "string"
          default: "example_username"
        password:
          type: "string"
          default: "example_password"
        age:
          type: "number"
          format: "int32"
          default: 17
      required:
        - full_name
        - username
        - password
        - age
    loginUser:
      type: "object"
      properties:
        username:
          type: "string"
          default: "example_username"
        password:
          type: "string"
          default: "example_password"
      required:
        - username
        - password
    user:
      type: "object"
      properties:
        full_name:
          type: "string"
          default: "example full name"
        username:
          type: "string"
          default: "example_username"
        age:
          type: "number"
          format: "int32"
          default: 17
    loginSuccess:
      type: "object"
      properties:
        token:
          type: "string"
          default: "example token"
        message:
          type: "string"
          default: "login success"
    loginInvalidCredentials:
      type: "object"
      properties:
        message:
          type: "string"
          default: "invalid username/password"

    article:
      type: "object"
      properties:
        title:
          type: "string"
          default: "example title"
        content:
          type: "string"
          default: "example content"
        likes_count:
          type: "number"
          format: "int32"
          default: 17
        author_id:
          type: "number"
          format: "int32"
          default: 1
        author:
          type: "object"
          properties:
            full_name:
              type: "string"
              default: "example barber full name"
            age:
              type: "number"
              format: "int32"
              default: 17
        category_id:
          type: "number"
          format: "int32"
          default: 1
        category:
          properties:  
            name:
              type: "string"
              default: "example category"
    postArticle:
      type: "object"
      properties:
        title:
          type: "string"
          default: "example title"
        content:
          type: "string"
          default: "example content"
        category:
          type: "string"
          default: "example category"
    postLikes:
      type: "object"
      properties:
        article_id:
          type: "number"
          format: "int32"
          default: 1


    errorInternalServer:
      type: "object"
      properties:
        message:
          type: "string"
          example: "internal server error"
        detail:
          type: "string"
          example: "error generated from err.Error() object"
    errorBadRequest:
      type: "object"
      properties:
        message:
          type: "string"
          example: "example error: name is required"
    errorNotFound:
      type: "object"
      properties:
        message:
          type: "string"
          example: "data not found"
    errorUnauthorized:
      type: "object"
      properties:
        message:
          type: "string"
          example: "invalid access token"
    errorForbidden:
      type: "object"
      properties:
        message:
          type: "string"
          example: "you're not authorized to perform this action"
          
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      
    
  responses:
    internalServerError:
      description: "internal server error; semua error lain seperti error bad request dan error not found"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorInternalServer"
    badRequest:
      description: "bad request error"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorBadRequest"
    notFound:
      description: "not found error"
      content:
        application/json:
          schema:
           $ref: "#/components/schemas/errorNotFound"
    loginFailedInvalidCred:
      description: "kesalahan username/password"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/loginInvalidCredentials"
    unauthorized:
      description: "kesalahan pada akses token yang disertakan di headers"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorUnauthorized"
    forbidden:
      description: "kesalahan pada hak akses yang dimiliki user yang sedang login(akses token)"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorForbidden"
    